"""Todo list entities for the Chores integration.

One list per child, holding the task occurrences due today. Ticking an item
completes it in Chores; unticking it un-completes it.
"""

from __future__ import annotations

from datetime import date
from typing import Any

from homeassistant.components.todo import (
    TodoItem,
    TodoItemStatus,
    TodoListEntity,
    TodoListEntityFeature,
)
from homeassistant.core import HomeAssistant, callback
from homeassistant.exceptions import HomeAssistantError
from homeassistant.helpers.device_registry import DeviceEntryType, DeviceInfo
from homeassistant.helpers.entity_platform import AddConfigEntryEntitiesCallback
from homeassistant.helpers.update_coordinator import CoordinatorEntity

from .api import ChoresError
from .const import CLASSIFICATION_OPTIONAL, DOMAIN
from .coordinator import ChoresConfigEntry, ChoresCoordinator

# An occurrence that has not been recorded yet has no id of its own, so items
# are keyed by the tuple CompleteTask actually takes. That way recorded and
# unrecorded occurrences are handled identically.
UID_SEPARATOR = "|"


def _uid(occurrence: dict[str, Any]) -> str:
    """Build the stable item id for an occurrence."""
    return UID_SEPARATOR.join(
        (
            occurrence.get("taskId", ""),
            occurrence.get("childId", ""),
            occurrence.get("dueDate", ""),
        )
    )


def _sort_key(occurrence: dict[str, Any]) -> tuple[int, str]:
    """Sort mandatory chores before optional ones, then by title.

    This mirrors the app's own "Must do" / "Can do" split.
    """
    optional = occurrence.get("classification") == CLASSIFICATION_OPTIONAL
    return (int(optional), occurrence.get("title", ""))


async def async_setup_entry(
    hass: HomeAssistant,
    entry: ChoresConfigEntry,
    async_add_entities: AddConfigEntryEntitiesCallback,
) -> None:
    """Set up a todo list for each child in the family."""
    coordinator = entry.runtime_data
    known: set[str] = set()

    @callback
    def _add_new_children() -> None:
        """Add lists for children that have appeared since the last refresh."""
        new = [child for child in coordinator.data.children if child["id"] not in known]
        if not new:
            return
        known.update(child["id"] for child in new)
        async_add_entities(ChoresTodoListEntity(coordinator, child) for child in new)

    _add_new_children()
    entry.async_on_unload(coordinator.async_add_listener(_add_new_children))


class ChoresTodoListEntity(CoordinatorEntity[ChoresCoordinator], TodoListEntity):
    """Today's chores for one child."""

    _attr_has_entity_name = True
    _attr_name = None
    # Occurrences are generated by the task's schedule, so creating, deleting
    # and reordering them here would be meaningless.
    _attr_supported_features = TodoListEntityFeature.UPDATE_TODO_ITEM

    def __init__(self, coordinator: ChoresCoordinator, child: dict[str, Any]) -> None:
        """Initialise the list."""
        super().__init__(coordinator)
        self._child_id = child["id"]
        self._attr_unique_id = f"{coordinator.family_id}_{self._child_id}"
        self._attr_device_info = DeviceInfo(
            identifiers={(DOMAIN, self._child_id)},
            name=child.get("name") or "Child",
            manufacturer="Chores",
            model="Child",
            entry_type=DeviceEntryType.SERVICE,
        )

    @property
    def _occurrences(self) -> list[dict[str, Any]]:
        """Today's occurrences for this child."""
        return self.coordinator.data.occurrences_by_child.get(self._child_id, [])

    @property
    def todo_items(self) -> list[TodoItem]:
        """Return today's chores as todo items."""
        return [
            TodoItem(
                uid=_uid(occurrence),
                summary=occurrence.get("title") or "Chore",
                description=occurrence.get("description") or None,
                due=_due_date(occurrence),
                status=(
                    TodoItemStatus.COMPLETED
                    # Zero values are omitted in proto3 JSON, so an absent
                    # completedAt is the whole signal for "not done".
                    if occurrence.get("completedAt")
                    else TodoItemStatus.NEEDS_ACTION
                ),
            )
            for occurrence in sorted(self._occurrences, key=_sort_key)
        ]

    async def async_update_todo_item(self, item: TodoItem) -> None:
        """Complete or un-complete a chore."""
        if item.uid is None:
            raise HomeAssistantError("Cannot update a chore without an id")

        occurrence = next(
            (o for o in self._occurrences if _uid(o) == item.uid),
            None,
        )
        if occurrence is None:
            raise HomeAssistantError("That chore is no longer due today")

        if item.summary and item.summary != occurrence.get("title"):
            raise HomeAssistantError(
                "Chores are renamed in the Chores app, not from Home Assistant"
            )

        task_id, child_id, due_date = item.uid.split(UID_SEPARATOR)
        try:
            if item.status == TodoItemStatus.COMPLETED:
                await self.coordinator.client.complete_task(task_id, child_id, due_date)
            else:
                await self.coordinator.client.uncomplete_task(
                    task_id, child_id, due_date
                )
        except ChoresError as err:
            raise HomeAssistantError(f"Could not update chore: {err}") from err

        await self.coordinator.async_request_refresh()


def _due_date(occurrence: dict[str, Any]) -> date | None:
    """Parse an occurrence's YYYY-MM-DD due date."""
    raw = occurrence.get("dueDate")
    if not raw:
        return None
    try:
        return date.fromisoformat(raw)
    except ValueError:
        return None
